services:
  backend:
    build: .
    # Используем скрипт ожидания БД в качестве команды запуска
    command: /app/wait-for-db.sh make run.server.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      # Удален db_volume, так как используется сетевой сервис PostgreSQL
      - static_volume:/app/backend/staticfiles
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - db # Явно указываем зависимость от сервиса базы данных

  db:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # !!! ИСПРАВЛЕННЫЙ СЕРВИС CELERY !!!
  celery:
    build: .
    command: make celery
    restart: always # Убрано дублирование этой строки
    volumes:
      # Правильный отступ и дефис перед элементом списка
      - static_volume:/app/backend/staticfiles
    depends_on:
      - backend
      - redis
    env_file:
      - .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  bot:
    build: .
    command: make run.bot
    restart: always
    depends_on:
      - backend
      - redis
    env_file: .env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  collectstatic:
    build: .
    command: make collectstatic
    env_file: .env
    volumes:
      - static_volume:/app/backend/staticfiles
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  static_volume:
  db_volume:
  pgdata:
