from .search import SEARCH_RESULT_TEXT
from .main import (
    MAIN_TEXT,
    NONE_FAVORITES_TEXT,
    FAVORITES_TEXT,
    TOP_CHAT_TEXT,
    MUSIC_CAPTION_TEXT,
    PLAYLISTS_TEXT,
)
from .admin import (
    STATS_MAIN_TEXT,
    STATS_EVENT_TYPE_TEXT,
    ADMIN_MAIN_TEXT,
    BROADCASTS_MAIN_TEXT,
    GET_FILE_INFO_TEXT,
    FILE_INFO_RESULT_TEXT,
    FILE_INFO_ERROR_TEXT,
    BROADCAST_RETRIEVE_TEXT,
    get_broadcast_retrieve_text,
)
